// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
//  ECMEET'26 — CENTRAL CONFIGURATION FILE
//  Crescent University | Edit this file to update events, teams, coordinators
//  ⚠️  Auto-generated by Event Manager.
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

const CONFIG = {
  "college": {
    "name": "Crescent University",
    "eventName": "ECMEET'26",
    "email": "ecmeet@crescent.education",
    "phone": "+91 99999 00000",
    "website": "https://crescent.education",
    "logo": "crescent_logo.png",
    "allowedDomain": "crescent.education"
  },
  "teams": [
    {
      "id": "gryffindor",
      "name": "Gryffindor",
      "colors": {
        "primary": "#740001",
        "secondary": "#D3A625"
      },
      "traits": "Bravery, Courage, Nerve",
      "logo": "logo_gryffindor.png",
      "corners": {
        "topLeft": "ic_top_left_corner_gryffindor.png",
        "topRight": "ic_top_right_corner_gryffindor.png",
        "bottomLeft": "ic_bottom_left_corner_gryffindor.png",
        "bottomRight": "ic_bottom_right_corner_gryffindor.png"
      }
    },
    {
      "id": "slytherin",
      "name": "Slytherin",
      "colors": {
        "primary": "#1A472A",
        "secondary": "#AAAAAA"
      },
      "traits": "Ambition, Cunning, Leadership",
      "logo": "logo_slytherin.png",
      "corners": {
        "topLeft": "ic_top_left_corner_slytherin.png",
        "topRight": "ic_top_right_corner_slytherin.png",
        "bottomLeft": "ic_bottom_left_corner_slytherin.png",
        "bottomRight": "ic_bottom_right_corner_slytherin.png"
      }
    },
    {
      "id": "ravenclaw",
      "name": "Ravenclaw",
      "colors": {
        "primary": "#0E1A40",
        "secondary": "#946B2D"
      },
      "traits": "Wisdom, Intelligence, Wit",
      "logo": "logo_ravenclaw.png",
      "corners": {
        "topLeft": "ic_top_left_corner_ravenclaw.png",
        "topRight": "ic_top_right_corner_ravenclaw.png",
        "bottomLeft": "ic_bottom_left_corner_ravenclaw.png",
        "bottomRight": "ic_bottom_right_corner_ravenclaw.png"
      }
    },
    {
      "id": "hufflepuff",
      "name": "Hufflepuff",
      "colors": {
        "primary": "#ECB939",
        "secondary": "#726255"
      },
      "traits": "Patience, Loyalty, Hard Work",
      "logo": "logo_hufflepuff.png",
      "corners": {
        "topLeft": "ic_top_left_corner_hufflepuff.png",
        "topRight": "ic_top_right_corner_hufflepuff.png",
        "bottomLeft": "ic_bottom_left_corner_hufflepuff.png",
        "bottomRight": "ic_bottom_right_corner_hufflepuff.png"
      }
    }
  ],
  "admins": [
    {
      "email": "admin@crescent.education",
      "name": "ECMEET Admin",
      "role": "admin"
    },
    {
      "email": "230171601108@crescent.education",
      "name": "Mohamed Riaz",
      "role": "dev"
    }
  ],
  "coordinators": [
    {
      "email": "coordinator1@crescent.education",
      "name": "Event Coordinator 1",
      "assignedEvents": [
        "hackathon",
        "codewars"
      ]
    },
    {
      "email": "coordinator2@crescent.education",
      "name": "Event Coordinator 2",
      "assignedEvents": [
        "techquiz",
        "appdesign",
        "paperpresets"
      ]
    }
  ]
};

module.exports = CONFIG;
